# SPDX-FileCopyrightText: 2023 Carmen Bianca BAKKER <carmen@carmenbianca.eu>
#
# SPDX-License-Identifier: CC0-1.0 OR GPL-3.0-or-later

[protokolo]
changelog = "CHANGELOG.md"
markup = "markdown"
directory = "changelog.d"
