# SPDX-FileCopyrightText: 2023 Carmen Bianca BAKKER <carmen@carmenbianca.eu>
#
# SPDX-License-Identifier: CC0-1.0 OR GPL-3.0-or-later

# This file doesn't presently do anything. It's an idea of what the
# configuration could look like.

[protokolo.version]
title = "{version} - {date}"

[protokolo.sections.added]
title = "Added"

[protokolo.sections.changed]
title = "Changed"

[protokolo.sections.deprecated]
title = "Deprecated"

[protokolo.sections.removed]
title = "Removed"

[protokolo.sections.fixed]
title = "Fixed"

[protokolo.sections.security]
title = "Security"
