# SPDX-FileCopyrightText: 2023 Carmen Bianca BAKKER <carmen@carmenbianca.eu>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1

[[annotations]]
path = "changelog.d/**.md"
precedence = "override"
SPDX-FileCopyrightText = "Protokolo contributors"
SPDX-License-Identifier = "CC-BY-SA-4.0 OR GPL-3.0-or-later"

[[annotations]]
path = ["po/protokolo.pot", "po/**.po"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Protokolo contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"
