# SPDX-FileCopyrightText: 2023 Carmen Bianca BAKKER <carmen@carmenbianca.eu>
#
# SPDX-License-Identifier: EUPL-1.2+

version = 1

[[annotations]]
path = "changelog.d/**.md"
precedence = "override"
SPDX-FileCopyrightText = "Protokolo contributors"
SPDX-License-Identifier = "CC-BY-SA-4.0 OR EUPL-1.2+"

[[annotations]]
path = ["po/protokolo.pot", "po/**.po"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Protokolo contributors"
SPDX-License-Identifier = "EUPL-1.2+"
