# SPDX-FileCopyrightText: 2024 Carmen Bianca BAKKER <carmen@carmenbianca.eu>
#
# SPDX-License-Identifier: GPL-3.0-or-later

on:
  push:
    branches: main
  pull_request:

jobs:
  pytest:
    runs-on: docker
    container: nikolaik/python-nodejs:python3.11-nodejs21
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: poetry install --no-interaction --only main,test
      - name: Run tests
        run: poetry run pytest --cov=protokolo

  pylint-mypy:
    runs-on: docker
    container: nikolaik/python-nodejs:python3.11-nodejs21
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: poetry install --no-interaction --only main,dev,test
      - name: Run pylint
        run: poetry run pylint src/ tests/
      - name: Run mypy
        run: poetry run mypy

  black-prettier-isort:
    runs-on: docker
    container: nikolaik/python-nodejs:python3.11-nodejs21
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          poetry install --no-interaction --only dev
          npm install prettier@3.0.3
      - name: Run black
        run: poetry run black .
      - name: Run prettier
        run: npx prettier --check .
      - name: Run isort
        run: poetry run isort --check src/ tests/

  reuse:
    runs-on: docker
    container: nikolaik/python-nodejs:python3.11-nodejs21
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install reuse==3.0.1
      - name: Run reuse
        run: reuse lint
